version: '3.7'

services:

  web:
    build: ./app
    command: gunicorn cruncher.wsgi:application --preload --bind 0.0.0.0:8000 
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    links:
      - rabbitmq
  celery:
    build: ./app
    command: celery --without-gossip --without-mingle --without-heartbeat -A cruncher worker -l info
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    env_file: .env.db

  rabbitmq:
    image: rabbitmq:3.7.8
