# Generated by Django 2.1.7 on 2019-03-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('project_name', models.CharField(help_text='User defined shorthand name for the analysis project', max_length=255)),
                ('email', models.EmailField(help_text='User provided email address', max_length=254)),
                ('analysis_type', models.CharField(help_text='Type of analysis to be performed', max_length=64)),
                ('raw_data', models.TextField(help_text='Raw data for analysis')),
                ('task_id', models.CharField(blank=True, help_text='Internal unique id for the analysis task', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
